### ISSUE TITLE
EDIT FEATURE: SNOMED ID disappearing

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#100]
This feature is assigned to a SNOMED ID, but the ID disappears in the feature edit view. 
When FIX SNOMED is clicked, nothing happens. although this feature does have parents in Kahun. 

http://kahuneditor-dev.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/feature/FE.df6cefb7-333d-4472-816e-ff959a32d36e

**Comment by kahunmedicaltal** [comment]
Happens as the concept is not active in snomed 2015 (which is the one we are using). This will be solved only once we shift to use the latest snomed edition
