### ISSUE TITLE
EDIT RULE: Remove relation not saved

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#107]
Trying to remove the relation=qualifier from TARGET, the UPDATE is saved successfully according to the alert message. 
When viewing the rule, the change was not saved.

http://kahuneditor-dev.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/ruleValue/RV.1498e1e6-6f24-438f-b132-9379aeea94ee
Remove procedure = history taking 
from TARGET
click update

**Comment by kahunmedicaltal** [comment]
should be fixed now
