### ISSUE TITLE
Duplicated view of qualifiers

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#118]
The original rule has a single "allergen" in the breakdown, while the display shows duplicated qualifier "allergen".
http://kahuneditor.s3-website-us-east-1.amazonaws.com/#/w-kahun/ruleValue/RV.a867e3d4-a242-4ff8-bb91-4c5218db386a

**Comment by kahunmedicaltal** [comment]
I see only one
<img width="1361" alt="screen shot 2019-02-24 at 19 19 56" src="https://user-images.githubusercontent.com/42319641/53302650-4ad97e80-3869-11e9-97ca-4ff2120d8cee.png">

**Comment by MichalKahun** [comment]
weird. maybe i was seeing double ... will let you know if happens again.
