### ISSUE TITLE
Cannot access rule view - goes blank

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#135]
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/rule/RU.f7bca652-f878-498f-a753-9202bc8b4ec8

This is the exception:

RU.f7bca652-f878-498f-a753-9202bc8b4ec8:1 GET http://ec2-54-210-58-88.compute-1.amazonaws.com/med/page/rule/RU.f7bca652-f878-498f-a753-9202bc8b4ec8 500 (Server Error)
index.html#/w-kahun/rule/RU.f7bca652-f878-498f-a753-9202bc8b4ec8:1 Access to fetch at 'http://ec2-54-210-58-88.compute-1.amazonaws.com/med/page/rule/RU.f7bca652-f878-498f-a753-9202bc8b4ec8' from origin 'http://kahuneditor.s3-website-us-east-1.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
ajaxbank.ts:595 response from $(comment) (error): {}
ajaxbank.ts:599 Uncaught (in promise) TypeError: Cannot read property 'status' of null
    at fetch.catch.then.response (ajaxbank.ts:599)
fetch.catch.then.response @ ajaxbank.ts:599
Promise.then (async)
fetchPage @ editPage.tsx:44
componentDidMount @ editPage.tsx:32
commitLifeCycles @ react-dom.development.js:17130
commitAllLifeCycles @ react-dom.development.js:18532
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18744
(anonymous) @ react-dom.development.js:20214
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20213
performWorkOnRoot @ react-dom.development.js:20142
performWork @ react-dom.development.js:20050
performSyncWork @ react-dom.development.js:20024
interactiveUpdates$1 @ react-dom.development.js:20291
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
2RU.f7bca652-f878-498f-a753-9202bc8b4ec8:1 GET http://ec2-54-210-58-88.compute-1.amazonaws.com/med/page/rule/RU.f7bca652-f878-498f-a753-9202bc8b4ec8 500 (Server Error)
index.html#/w-kahun/rule/RU.f7bca652-f878-498f-a753-9202bc8b4ec8:1 Access to fetch at 'http://ec2-54-210-58-88.compute-1.amazonaws.com/med/page/rule/RU.f7bca652-f878-498f-a753-9202bc8b4ec8' from origin 'http://kahuneditor.s3-website-us-east-1.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
ajaxbank.ts:595 response from $(comment) (error): {}
ajaxbank.ts:599 Uncaught (in promise) TypeError: Cannot read property 'status' of null
    at fetch.catch.then.response (ajaxbank.ts:599)

**Comment by kahunmedicaltal** [comment]
fixed
