### ISSUE TITLE
Multiple ifs: new citation erases old

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#14]
Example: 
SOURCE #1: 6 cases per million per year in the United Kingdom 
SOURCE #2: Up to 11 per million per year in North America 

![image](https://user-images.githubusercontent.com/42371975/47270725-99ec6b80-d578-11e8-8b6e-6d91e698c80a.png)

**Comment by kahunmedicaltal** [comment]
That is true. 

Currently, if we have a few "incidence" rules for a disease, we use the last instance only.

It applies to all rules BTW, if you have two citations for FEVER in FLU, we would use the last rule only. We also never mix/match numbers from two rules. Not sure this is wise but this is the way we work.

**Comment by MichalKahun** [comment]
ok. tnx
