### ISSUE TITLE
Rule without target

### ISSUE THREAD

**Issue by shaharov** [kahunmedical/kne#144]
There is no target in the rule :  

[RU.3a5bc939-519f-4206-aa3d-2c380ddaa731](http://kahuneditor.s3-website-us-east-1.amazonaws.com/#/w-kahun/rule/RU.3a5bc939-519f-4206-aa3d-2c380ddaa731)

Not sure what is the purpose of this rule but it can cause to some bugs.

**Comment by kahunmedicaltal** [comment]
Added "problems" menu to detect those
