### ISSUE TITLE
reminder - change history broken into pages

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#148]

**Comment by alex8080** [comment]
@kahunmedicaltal in order to support pagination we need a way to query the total number of commits available on the server. Would it be possible to extend the commits page to include this information?

**Comment by kahunmedicaltal** [comment]
added "totalCount" to the commits page response.

public class WCommitsPage {
	
	public ImmutableList<WCommit> commits;
	public Map<String, ModerateEnable> moderate;
	public int totalCount;
	public WStore store;

**Comment by alex8080** [comment]
@kahunmedicaltal thank you. I've extended WCommitsPage type definition to include totalCount and created a pull request in the kne.common-wtypes repository.
