### ISSUE TITLE
Patient Diagnosis: option to select a suggested test 

### ISSUE THREAD

**Issue by eitan-ron** [kahunmedical/kne#16]
make it easier to add cases - by selecting tests from the suggested lists and adding their results

**Comment by alex8080** [comment]
Hi @eitan-ron, 

Currently will only add the test to the case. I'll have to understand more to pre-populate the findings.

**Comment by eitan-ron** [comment]
what i had in mind was to help the following scenario:
Once i finish adding finding and run Diagnose  i get a list of suggested tests.

The idea was to be able to select a test from that list in order to add it to the finding section. and then manually add results to that test.  (e.g. Low/Norm/High, etc depending on the test).

Its not a very important one...as for now we can do without it..
