### ISSUE TITLE
Procedures migrated lost their SNOMED code

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#163]
Procedures that were migrated automatically lost their SNOMED id on the way. (They still have the correct name, but no ID)
Any way we can search for the corresponding ID from snomed?

**Comment by MichalKahun** [comment]
Example:http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/featureEdit/FE.4c1a0550-8fb5-48bd-9f85-2b3e29e07473

NO snomed ID

**Comment by MichalKahun** [comment]
not yet solved

**Comment by kahunmedicaltal** [comment]
@MichalKahun - I have gone over all features and added snomed concept (by matching their names to the snomed name). The change is waiting for your moderation. Please review and approve.

**Comment by MichalKahun** [comment]
looks great. thanks. closing issue.
