### ISSUE TITLE
Negation - improve indicator of negated rules in editor

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#164]
Example:
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/feature/FE.601027aa-2787-4f03-8613-c6c41f3b9c38

Looking at the negated rule, it's hard to notice that the probability is of the negated finding unless you look inside the rule. 
![image](https://user-images.githubusercontent.com/42371975/54525062-09298880-497c-11e9-9e2f-cb228bc54c4d.png)

**Comment by avgurf** [comment]
Merged in https://github.com/kahunmedical/kne.fe/pull/221
