### ISSUE TITLE
Intermediate complication should not be suspected

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#169]
Patient findings should rule out complications in the path:

1. Anemia suspected in the path between menkes and > fatigue
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.3117f564-d552-4443-92fe-6108975da5a8
![image](https://user-images.githubusercontent.com/42371975/55876942-71e1da80-5ba1-11e9-987a-121130ea0c25.png)

2. wiskot is suspected because of splenomegaly, the patient is said no to have enlarged spleen:
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.835fc97a-c0c1-44e1-8f5d-6165bb0b6ac9

**Comment by MichalKahun** [comment]
Another example:
3. Thrombocytopenia should not be suspected in the path of other diseases since the patient platelet count in normal. 
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.b7d926e0-c7f6-4126-873d-597982d6ddfa

**Comment by kahunmedicaltal** [comment]
@MichalKahun - the 1st issue (anemia) should be solved now.

regarding the two others - I need to better understand the issue. Lets discuss (if possible, please attach a screenshot as you did for anemia)

**Comment by MichalKahun** [comment]
the two other issues seemed to be resolved too.
