### ISSUE TITLE
Rule format: target with relation "procedure"

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#176]
We need to clean the rules that have the old format:
A > B:procedure = XX

example: Disease causes symptom using procedure "physical examination"

Before migration i think i fixed most of these. But, i still see these popping up sometimes.

**Comment by kahunmedicaltal** [comment]
@MichalKahun - not sure I understand the problem here. Could you please give me an example?

**Comment by Michalzu** [comment]
Example:
http://kahuneditor.s3-website-us-east-1.amazonaws.com/#/w-kahun/rule/RU.1316fab2-45c2-4e8e-9fde-8327ed4e6d89

The procedure should be in a separate rule stating the sensitivity of the physical respiratory examination in detecting the chest dullness. The procedure should be removed from the rule using the finding in the target. 
Could you show these in the PROBLEMS. if they are not too many, i will fix manually.

**Comment by MichalKahun** [comment]
issue open
