### ISSUE TITLE
Achalasia case 

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#183]
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.c9afe26f-f8f7-4f17-b3e8-37b90922a3a8

1. No-specific symptoms influencing DD. Example: chronic pancreatitis suspected due to weight loss

(prevealence should fix)

2. Etiology rule: Chronic pancreatitis caused by alcohol abuse. 
Missing alcohol abuse -> chronic pancreatitis?

(try to reverse "target cause source" using prevalences)

2. Suspecting disorder with different primary causes. Example: suspecting exudative pleural effusion due to schatzki ring and due to TB.

3. Not showing qualifiers in path. 
example:Difficulty swallowing fluid (finding)

4. parent and children suspected with same probability:
Neoplasm of esophagus  
Adenocarcinoma of esophagus  
Malignant tumor of esophagus  
Squamous cell carcinoma of esophagus  

5. Solver not using risk factor:
Smoker

**Comment by kahunmedicaltal** [comment]
these are the numbers from COHD:

chronic pancreatitis: 1862
alcohol abuse: 17588
co-occurrence: 236

**Comment by MichalKahun** [comment]
cannot reproduce the same issues :) 
This is the same case, now giving great DDx list

http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.96ddd9f6-5ebf-4c35-b735-42a684b67ae6
