### ISSUE TITLE
Wilson case - improved reasoning w/o lambdaStructure

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#185]
http://kahuneditor.s3-website-us-east-1.amazonaws.com/#/w-kahun/caseEdit/CS.cb32303c-734c-4802-9744-a5d29a2d2af0
Look at the reasoning of :8.  
Non-alcoholic steatohepatitis (disorder)

**Comment by kahunmedicaltal** [comment]
Michal - 
I hope this is fixed. Please test

Details:
We have a new flag: isaAsAssociation. Enabling it, treats ISA relations as ASSOCIATION (instead of causality). In practice this should remove paths such as A = B <= C => D

**Comment by MichalKahun** [comment]
In the wilson case this seems to work. With the new isaAsAssociation the reasoning and DD looks much better. 

But something came up now, in a different case. 
When i uncheck the new flag, i get path that was missing before
A > B = C > D
Please look at this case:
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.661fc4ac-5373-4a66-b138-015018c416fa
diagnose the case with the isaAsAssociation flag UNCHECKED.
Look at the reasoning of Number 3: Carbon monoxide poisoning  
This is correct path. But it is lost if we check the isaAsAssociation.
![image](https://user-images.githubusercontent.com/42371975/55865845-d728d200-5b87-11e9-8320-1e3e4f8d855b.png)

**Comment by kahunmedicaltal** [comment]
Thanks! I will take a look

**Comment by kahunmedicaltal** [comment]
Michal - let me know if it looks better now

**Comment by MichalKahun** [comment]
mucha better !!! thanks
