### ISSUE TITLE
Main etiology of disease negated. Disease still suspected. 

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#192]
Negative prediciton not strong enough.
Chemical esophagitis is caused by ingestion of toxic substance in 99%.
Patient has negative finding, and disorder is still suspected. 
![image](https://user-images.githubusercontent.com/42371975/55936475-1ebe6500-5c3f-11e9-90ea-cfb6cc176ea6.png)

**Comment by kahunmedicaltal** [comment]
http://kahuneditor.s3-website-us-east-1.amazonaws.com/#/w-kahun/caseEdit/CS.eee9b69b-3d35-4242-ac14-0493f9995077

negate the last finding

**Comment by kahunmedicaltal** [comment]
We have a disease D and etiology E.

We have rules
1. D->99%->E
2. E -> 16% -D
Prevalences are incorrect as both are not specified in COHD (and therefore the same)

As the system uses the second rule, result is wrong. Once the second rule is removed, result is correct.

**Comment by kahunmedicaltal** [comment]
In case we had both a path "from finding to disease" and "from disease to finding". In such a a case the solver used to prefer the one following the causal direction. As E above is Etiology, the solver used the path 

E -> 16% -> D

We now changed it to always prefer using the path from disease to finding. Therefore we use the path:

D -> 99% -> E

Seems as this solved this specified case. 

@MichalKahun - please check
