### ISSUE TITLE
Target causes source

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#197]
A>B
B is the etiology of A

A: alcohol abuse
B: Chronic pancreatitis

Chronic pancreatitis should not be suspected high. Looks like it suspects it based on the etiology rule. 

http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.96ddd9f6-5ebf-4c35-b735-42a684b67ae6

![image](https://user-images.githubusercontent.com/42371975/56092248-35c0b980-5ec2-11e9-8990-b0062951f2d3.png)

**Comment by kahunmedicaltal** [comment]
Kahun now prefers to use the CP > AB rule (40-50%) over the AB > CP rule. However, the problem still exist.

I changed (locally) the CP > AB rule from 40-50% to 10% and CP was pushed from being  #2 to #11

Not yet sure what's the solution here

**Comment by kahunmedicaltal** [comment]
@MichalKahun - following what you are saying, seems as we should distinguish between sign/symtoms that the disease should explain and ones that are part of the patient's background.

For example, GENDER and AGE should not be explained. FATIGUE and WEIGHT LOSS on the other hand should be explained.

Seems as SMOKER and ALCOHOL ABUSE are more like AGE and GENDER than like FATIGUE and WEIGHT LOSS. Currently both FATIGUE and SMOLER are SIGN/SYMPTOM and as such Kahun treats them the same.

Can we somehow mark SMOKER and ALCHOL ABUSE as ETIOLOGY/BACKGROUND (i.e. set then in a special KAHUN CATEGORY). Does it make sense?

**Comment by kahunmedicaltal** [comment]
Seems as the "extraEtiologySmoothFactor" solves this issue

**Comment by kahunmedicaltal** [comment]
@MichalKahun - closing...
