### ISSUE TITLE
Finding highly prevalent in disease, but shows no correlation

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#198]
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.f318ad21-e7b7-476a-9ae6-ea98a8755012

![image](https://user-images.githubusercontent.com/42371975/56092387-3b1f0380-5ec4-11e9-9a74-f57ea1b18930.png)

**Comment by shaharov** [comment]
The main problem is that the prevalences are inconsistent with the rules. I.e., the prevalence of Cardiac tarponade is X ,  the prevalence of Pulsus paradoxus is 0.5X but we have the rule  "Cardiac tarrponade -> pulsus paradoxus with rate 95%" , which contradict the prevalence of pulsus paradoxus (it should be at least 0.95X) 

Some other issues we found in that case : 
1. It seems like the prevalence of Orthopnea is too low, can you check it, @MichalKahun ?  (1 to 2500)
2. We think that  there should be a rule between Cardiac tamponade and  Orthopnea.

**Comment by MichalKahun** [comment]
@josephmermel 
There is probably also an issue with the display here.

**Comment by kahunmedicaltal** [comment]
Display issue (no correlation) now fixed
