### ISSUE TITLE
Edit feature: change from LAB to COMPLICATION

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#20]
This option should be disabled or limited. 
In case the type of feature is changed, the rules are no longer visible within the editor. But are still found in the exported spreadsheet. 

Example:
feature NEPHROTIC RANGE PROTEINURIA was chnaged from LAB to COMPLICATION. 
![image](https://user-images.githubusercontent.com/42371975/47837671-88476700-ddb5-11e8-9e1b-fbb9e6d2b3c7.png)

**Comment by kahunmedicaltal** [comment]
@MichalKahun - this is supposed to work better now. Please check and if ok close this issue
