### ISSUE TITLE
Prevalence larger than 1

### ISSUE THREAD

**Issue by eitan-ron** [kahunmedical/kne#201]
![prevalence](https://user-images.githubusercontent.com/42339123/56471294-8784b900-6459-11e9-9074-6a9d2c461320.png)

**Comment by shaharov** [comment]
The prevalences are percentages, not probabilities.  The numbers between 0 and 100. 
Maybe @josephmermel should add the sign '%' next to it, or @kahunmedicaltal should divide it by 100.
