### ISSUE TITLE
PANELS: once panel added and a finding is deleted from panel, the case crashes and cannot be reopened

### ISSUE THREAD

**Issue by eitan-ron** [kahunmedical/kne#210]
The case
"A 32-Year-Old Man Vomiting Blood"  is stuck.
Can't open.  I suspect it happened after i added a blood panel

**Comment by kahunmedicaltal** [comment]
http://kahuneditor.s3-website-us-east-1.amazonaws.com/#/w-kahun/caseEdit/CS.cd384e35-6f8f-44d3-9e30-5aae37d9a10b

**Comment by kahunmedicaltal** [comment]
@josephmermel - could you please take a look

**Comment by MichalKahun** [comment]
this case also does not open:

http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.6194539c-b4cf-49a2-98d9-881c3000536d

**Comment by MichalKahun** [comment]
another case:

http://kahuneditor.s3-website-us-east-1.amazonaws.com/#/w-kahun/caseEdit/CS.1dfa2435-eba0-4f70-b28b-238d1553aabc
