### ISSUE TITLE
Patient Diagnosis: thrombocytopenia case

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#22]
after i add the third rule (platelets normal) i expect kahun not to suspect thrombocytopenia any more.

![image](https://user-images.githubusercontent.com/42371975/47907458-f8c4b580-de93-11e8-9955-8a22e8ebbf59.png)
![image](https://user-images.githubusercontent.com/42371975/47907523-198d0b00-de94-11e8-8f09-ee12af7de93f.png)

**Comment by kahunmedicaltal** [comment]
as far as i could see it does not list **thrombocytopenia**

**Comment by MichalKahun** [comment]
i cannot reproduce the 'thrombocytopenia' in the complication list.

**Comment by kahunmedicaltal** [comment]
You are right. I will take a look

**Comment by kahunmedicaltal** [comment]
Looked again. This is the case we speak about a lot:
                  
A ==> B ==> C
           |
           +==-> D

A = Shwachman-Diamond syndrome
B = thrombocytopenia
C = Petechiae of skin
D = Platelets [#/volume] in Blood

i.e. A causes B and B causes both C and D. If C is positive but D is negative it means we dont have B and therefore not have A

Kahun takes this into account but only in the "Complex Options", "Final List" and "Tests"  tables. 

The "disease", "complications" as well as the "reasoning popups" does not take these cases into account.

Is there also a problem with the final diagnose or next to perform tests list?
