### ISSUE TITLE
EDITOR: clickable disorders and rules in CASES

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#229]
![image](https://user-images.githubusercontent.com/42371975/57581439-0781ca00-74c0-11e9-89f5-bb5a631a7362.png)
![image](https://user-images.githubusercontent.com/42371975/57581446-36983b80-74c0-11e9-8544-09c2d7cbdc5d.png)

**Comment by avgurf** [comment]
Added in https://github.com/kahunmedical/kne.fe/pull/219
