### ISSUE TITLE
Feature view: show type of feature

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#23]
Top of the feature view page, show the type of feature: COMPLICATION, LAB, SYMPTOM, etc.

**Comment by alex8080** [comment]
Hi @MichalKahun,
Could you help me better understand what page do you have in mind? 

When I  open Kahun editor
and click on "Features" 
and then select "Personality Change (finding)" from the dropdown
Then I am presented with the "Edit Feature" page which shows "Type of Feature".  

So I guess there is another "Feature" page. Could you describe the steps to open it?

Thank you so much,
   Alex

**Comment by MichalKahun** [comment]
@alex8080 Looking at the added 'Parents' list i notice it shows all parents. This may be confusing. 
I suggest we show the immediate (first degree) parents.
And another list with first degree children. 

Later it would be better to present a collapse-expand tree-like view with all parents and children. 
For now, it may be sufficient to just be able to view first degree parents and children. And the user can navigate using the links to view further hierarchy of the tree.

**Comment by kahunmedicaltal** [comment]
Done by Alex
