### ISSUE TITLE
Cases feature: add finding after run

### ISSUE THREAD

**Issue by eitan-ron** [kahunmedical/kne#24]
Once i submit a case for diagnosis - i can't go back and add findings

**Comment by alex8080** [comment]
Hi @eitan-ron,
Could you describe the steps, please? I tried the following, but could not reproduce the issue:

1. open Kahun editor
2. click on "Cases"
3. click on "New Case"
4. fill in description "A case for diagnosis"
5. fill in findings "VITAL SIGNS", "Body mass index, (BMI) [RATIO]", "GROWTH CURVES", "<16.5"
6. click on "Diagnose Case"
7. add in findings "GENETIC_MUTATION", "MUTATION IN STK11 GENE", "Genetic test (procedure)", "Y"
8. click on "Diagnose Case"

**Comment by eitan-ron** [comment]
I used the same steps as above,  different disease.   
Anyway.  I could not reproduce the bug  -  its fine now.
