### ISSUE TITLE
SOLVER: redundant disorder appearing as non-redundant

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#240]
The patient should be suspected of Ileitis. 
Other disorders (sub-types of ileitis) are also suspected with no obvious reason. 

http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.1e4b988f-fdff-4d7e-8583-87a3e61837ca

![image](https://user-images.githubusercontent.com/42371975/57687675-84d64780-7644-11e9-9ead-e7c9c1d7eb0c.png)

**Comment by shaharov** [comment]
Fixed bc32e3b2040c19eff3b35757e4813f4a58a9fce4
