### ISSUE TITLE
EDITOR: do not allow adding new feature with same SNOMED ID

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#264]
This happens a lot, user adds new features and give a different name to the feature that already exists with the same SNOMED ID. 
Please add an alert in these cases. 
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/featureEdit/new/FEATURE
![image](https://user-images.githubusercontent.com/42371975/58802626-541b7980-8616-11e9-9203-34b04f9120e9.png)

**Comment by kahunmedicaltal** [comment]
fixed
