### ISSUE TITLE
ISA's prevalences override accurate prevalences

### ISSUE THREAD

**Issue by shaharov** [kahunmedical/kne#270]
The prevalence of Heart failure is 2%, given by [a rule](http://kahuneditor.s3-website-us-east-1.amazonaws.com/#/w-kahun/rule/RU.23f2cffe-07e6-4673-9358-23bd364f3508).
The prevalence of right heart failure is given by Roee's sheet -- 5%. 

The 'bottomUpRecursive' set the prevalence of a parent to be at least the prevalence of its children , which in that case override the prevalence of Heart failure given by the rule.

**Comment by kahunmedicaltal** [comment]
Good one. Tnx

@MichalKahun - how would you treat those cases?

**Comment by MichalKahun** [comment]
If either parent or child is a cited rule, this rule should dominate over the Roee estimation. Meaning, the child, in this case, cannot be higher than 2%. 
Will that work?
