### ISSUE TITLE
source of prevalence not clear - Bacterial Gastroentritis

### ISSUE THREAD

**Issue by eitan-ron** [kahunmedical/kne#271]
Kahun DD shows:
Bacterial gastroenteritis INF
Prevalence in General Population:  5.000

Roee's sheet - no estimate
Rules - We don't have a rule (also no such rules for parent/child)
In COHD = its 0.02%

**Comment by kahunmedicaltal** [comment]
maybe I have the wrong spreadsheet. mine shows roees as 2 (=5%)


FE.90082342-6723-4c22-a1a2-980fd9809537 | Bacterial gastroenteritis (disorder) | Bacterial gastroenteritis | Bacterial gastroenteritis | NAME CHECKED |   |   | Bacterial gastroenteritis;Bacterial gastroenteritis (disorder) | Kahun disorders | FEATURE | **2** | 4 | RV.02c43d76-bbf7-4d54-afb2-06c6e02776ac | 200/100000.0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by eitan-ron** [comment]
your spreadsheet is good.  
I was working on the one in which i compared Roee vs. COHD,   for some reason 
bacterial gastroentritis does not show up on the 2500 COHD list i worked with , so it was filtered out.
