### ISSUE TITLE
SOLVER: redundant disorders appearing in DD

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#284]
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.e07fb09a-5b49-4ca3-b7e9-065d87eba821

![image](https://user-images.githubusercontent.com/42371975/59565367-61dfee80-905b-11e9-8f15-fe5a8caa7d6e.png)

**Comment by shaharov** [comment]
fix https://github.com/kahunmedical/kne.graphql/commit/feb914db6822c75e1956761dcacfd5758d042381
