### ISSUE TITLE
Diagnose wont run with history finding

### ISSUE THREAD

**Issue by eitan-ron** [kahunmedical/kne#29]
1. try to run the case of A child with gastrointestinal bleeding
2. If you remove the travel history finding - it runs.

**Comment by alex8080** [comment]
I tried to run the case. The server returns 500:
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 Request failed.</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /med/diagnose. Reason:
<pre>    Request failed.</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>

**Comment by kahunmedicaltal** [comment]
@eitan-ron  Which feature exactly (for travel history) were you using? could you please save the case and attach the URL to the bug.

**Comment by kahunmedicaltal** [comment]
The bug I did found (and fixed):
In case you specified in a case a feature that did not appear in ANY of rule, diagnose did not work.

However, in your case "detail of history of foreign travel" does appear in a rule (http://ec2-18-217-18-129.us-east-2.compute.amazonaws.com/#/w-kahun/rule/RU.851bb554-41d4-46e6-b2d8-da270e357a31)

In any case, as it works now, lets close the bug.
