### ISSUE TITLE
SOLVER: missing path to pruritus

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#295]
missing path:
Budd-chiari -> cholestasis -> pruritus

![image](https://user-images.githubusercontent.com/42371975/59756508-8a056280-9292-11e9-9b9e-34540d740f21.png)

**Comment by shaharov** [comment]
fix https://github.com/kahunmedical/kne.graphql/pull/142/commits/785c9d32be7527286f83f0218223e3c5643e7150
