### ISSUE TITLE
EDITOR-CASES: request for new CONDITION

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#308]
Add "Self / Descendants / Self and descendants" to each feature added in the conditions 

![image](https://user-images.githubusercontent.com/42371975/60160342-d5bd8c00-97fd-11e9-9ef4-8841b583868e.png)

**Comment by kahunmedicaltal** [comment]
@MichalKahun - could you please add to this issue a case example for which this condition would help

**Comment by MichalKahun** [comment]
In this example: 
Glomerulonephritis  - or any of it's sub-types , should come in the top 20.
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.45530b5f-a9d7-42c4-8aa9-bcc39aed262e
![image](https://user-images.githubusercontent.com/42371975/60262570-1ba24f00-98e7-11e9-9853-bd6e727265c0.png)

![image](https://user-images.githubusercontent.com/42371975/60262527-02010780-98e7-11e9-9d66-32ac7ce9cc52.png)

**Comment by avgurf** [comment]
We decided to have only self and self and descendants
