### ISSUE TITLE
SOLVER: Lab test sensitivity appear wrong in DV

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#309]
The indirect rules from disorder to HIGH, NORMAL, LOW should be redundant if a direct path exists from disorder to lab test level. 

http://kahuneditor.s3-website-us-east-1.amazonaws.com/#/w-kahun/caseEdit/CS.80457991-b806-4bf3-b338-c5a17fff2a2e

![image](https://user-images.githubusercontent.com/42371975/60176235-67d58c80-981e-11e9-9453-546a29c1399f.png)

**Comment by MichalKahun** [comment]
Another example:
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.319a96eb-18bb-44f3-893c-656dcc7c48c3
![image](https://user-images.githubusercontent.com/42371975/60509962-e9be2d80-9cd6-11e9-8726-c81d9497ebc6.png)

**Comment by shaharov** [comment]
This specific bug is fixed, but a another closed-set related issue is opened : https://github.com/kahunmedical/kne/issues/329
