### ISSUE TITLE
EDITOR/DISEASE VIEW: add flag on features as 'group by'

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#331]
To help make the disease view 'readable':

For the Grouping by in the disease view, we should mark features as "interesting to group by".
Findings which are sub-types of these features will be grouped by the feature.
The features that are NOT "interesting to group by" will be ignored in the disease view. (Unless there are direct rules to these features. 

By default, all features should be marked as "interesting". We will manually UNMARK the rest.

**Comment by kahunmedicaltal** [comment]
Done by Avi and Shahar
