### ISSUE TITLE
Procedures ignored?

### ISSUE THREAD

**Issue by eitan-ron** [kahunmedical/kne#345]
http://kahuneditor.s3-website-us-east-1.amazonaws.com/#/w-kahun/caseEdit/CS.4048b458-9dc7-4132-842b-94b4ba7a68d3

The case uses a colonoscopy procedure, which rules out Crohn's
Yet Crohn's (exacerbation) comes up high.     When removing the procedure and simply negating Crohn's,  results do not contain Crohn's exacerbations

**Comment by kahunmedicaltal** [comment]
We miss the rule:

Given [Crohn] then [Crohn with procedure colonoscopy] 

Please add such a rule (with the correct sensitivity) and try again
