### ISSUE TITLE
EXPORT: complications are listed in spreadsheet as ASSOCIATIONS

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#36]
![image](https://user-images.githubusercontent.com/42371975/48885969-ce32a080-ee32-11e8-931d-1f302c175a5c.png)
![image](https://user-images.githubusercontent.com/42371975/48885987-dbe82600-ee32-11e8-925d-636d53b946c7.png)

**Comment by kahunmedicaltal** [comment]
Yes, should have warned you about this.

This is part of the change we have talked about Tuesday. We now have a limited set of rule types. I used ASSOCIATION for what we called the "General If/Then rule" in the PDF containing the new "uber" rule we  have discussed.

In addition/instead you now have 3 new fields: template, units, reversed. These set up the template used to create the rule, the unit used and if the rule is reversed (i.e. in practice the THEN feature is causing the IF feature)
