### ISSUE TITLE
SOLVER: hematuria DD - Bladder cancer

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#373]
Disorders coming up high in DD as a result of an existing risk factor (smoker). i think. The other findings are not typical in the disorders. 
I tried to look in the debug spreadsheet, and i'm not sure why these disorders are suspected. 

This is the case:
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.0fcaf323-b85b-4b1b-9e1c-55085daa9226
![image](https://user-images.githubusercontent.com/42371975/61994934-618b3800-b08a-11e9-9e8c-ccc3bfe07110.png)

**Comment by kahunmedicaltal** [comment]
@MichalKahun - closing this one
