### ISSUE TITLE
SOLVER: finding not correlated, should be path inherited from parent

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#378]
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/caseEdit/CS.b711327a-8aaa-4634-a17a-2a8522e3d42e

![image](https://user-images.githubusercontent.com/42371975/62007099-2d7b4a00-b152-11e9-80b5-935df4ef67ce.png)

![image](https://user-images.githubusercontent.com/42371975/62007089-0fade500-b152-11e9-9712-1a8e3cddd911.png)

**Comment by shaharov** [comment]
@kahunmedicaltal  there is a  V-Structure here and I'm not sure if it consistent with our decisions:

The missing path is [Afferent loop syndrome (disorder)](http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/feature/FE.a61c3798-b1ff-48be-bed6-df11fe14e3fb) **_is type of_**  [Postgastric surgery syndrome (disorder)](http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/feature/FE.dd92e83c-b9b9-45ef-b3db-1dc7ea614bd8)  [**_associated with_**](http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/rule/RU.4ef9f0c1-f24d-448e-9c5e-6e7411bbe60e)  Population|History of Operation on stomach (procedure)

We ruled out this path -- we counted the first edge (SEdgeISA) as a SourceCauseTarget, then the second edge is association (opposite to the previous one) , so we got V-Structure. 
What do you think?
