### ISSUE TITLE
APP: Troponin LAB TEST cannot assign HIGH/NORMAL/LOW

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#388]
Example:
FE.048766ff-ded7-4e84-97ad-67b6b29ff4d9

**Comment by oriharel** [comment]
No issue here. I tried with the cardiac word in the title and they both have mandatory level. If you select Troponin alone - this doesn't have level field. Perhaps you should take out troponin?

**Comment by kahunmedicaltal** [comment]
following @oriharel comment: troponin is a child of "LABORATORY TESTS" and not of "LABORATORY TESTS WITH LEVEL"
