### ISSUE TITLE
Case entry: adding a field for link 

### ISSUE THREAD

**Issue by eitan-ron** [kahunmedical/kne#39]
Would be good to have an additional field to enter the link for the source of a case.
And if at it - also a place for comments.

(i dont think we need all the other fields we save for data entry e.g. publication name, chapter, page, book...)

**Comment by alex8080** [comment]
@kahunmedicaltal when I try to send publication data to the server I am getting the following error:

`Unrecognized field "publication" (class com.kahun.web.model.WCase), not marked as ignorable (7 known properties: "panelids", "diagnoseTestids", "diagnoseDisorderids", "id", "description", "pileid", "evidences"])
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@75c3ab68; line: 1, column: 248] (through reference chain: com.kahun.web.resources.CaseResource$SaveCaseRequest["wcase"]->com.kahun.web.model.WCase["publication"])`

Could you take a look, please?

**Comment by kahunmedicaltal** [comment]
taking a look

**Comment by kahunmedicaltal** [comment]
turned out an old version was running on the server. should be working fine
now

**Comment by kahunmedicaltal** [comment]
fixed by Alex
