### ISSUE TITLE
CRP path request

### ISSUE THREAD

**Issue by kahunmedicaltal** [kahunmedical/kne#430]
Solver should return all paths (WITH SPECIFIC RULES) that end with a subtype of CRP

**Comment by shaharov** [comment]
@josephmermel , can I close this issue ? (I see that some patch were given here https://github.com/kahunmedical/kne.mobile/commit/901b906612f3386e9d25fe36a2cd2ab782be7f1f)

**Comment by josephmermel** [comment]
Yes I think so
