### ISSUE TITLE
Error when trying to delete the rule

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#51]
Not sure how I made this happen, I suspect something to do with approving the rule and then making changes to procedures of the rule. 
But now I cannot delete this rule:
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/rule/RU.adaf5c9a-a847-4b55-a7b4-c10f412fd34f
I want to delete this feature: 
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/feature/FE.22b7134b-714a-47ad-916c-cea5fb0a3449

**Comment by MichalKahun** [comment]
I think this bug is back: cannot delete a rule. i delete it, but the original rule still found. No error message. 

http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/ruleValue/RV.a9423932-b290-4d5d-8670-f5d3a7dc4596

i suspect this has something to do with IMAGING finding that has no finding, only procedure.

**Comment by kahunmedicaltal** [comment]
I have just clicked delete and the rule was deleted. please re-check.
