### ISSUE TITLE
Cannot add parent to feature : SAVED FAILED

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#53]
In edit feature, after adding parent i get error "saved failed" 
Example: http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/featureEdit/FE.64fbe819-62ce-4d53-9a4e-6520a0df0195
Try to add GOITER as a parent
![image](https://user-images.githubusercontent.com/42371975/50450819-eec1af00-0938-11e9-8043-490961f40bad.png)

**Comment by MichalKahun** [comment]
Another example:
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/featureEdit/FE.832cd2ca-6e7f-4398-9367-aefc183fb01c

trying to add parent: Disorder of vagus nerve

**Comment by kahunmedicaltal** [comment]
I assume this is fixed. Closing
