### ISSUE TITLE
Option to add comment before REJECTing a rule

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#55]
![image](https://user-images.githubusercontent.com/42371975/50481621-428cd080-09eb-11e9-912c-73da95d1bba3.png)

**Comment by alex8080** [comment]
@kahunmedicaltal I'll make the UI changes. Will need backend support for this.
@MichalKahun would you like "comment" to be available for reject only or for approve as well?

**Comment by MichalKahun** [comment]
Reject is enough. thank you.

**Comment by kahunmedicaltal** [comment]
@alex8080 - I will add a "comment" field to WCommit

**Comment by kahunmedicaltal** [comment]
@alex8080 

1. added comment field for WCommit
2. /commits/approve and /commits/reject now get a "comment" field. i.e. use:
        const body = { commitid: commitid, comment: comment };
3. (this is not part of this feature request ...) all the /*/save commands (i.e. /rules/save, /features/save..) now get a new "commitComment" field which would be saved as part of the commit

**Comment by kahunmedicaltal** [comment]
Fixed by @alex8080
