### ISSUE TITLE
Cannot edit original rule

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#56]
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/rule/RU.c9091a2e-6077-41c3-806e-eb39deaa722a
When clicked open a blank page
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/ruleValue/RV.d729a761-9c28-42d4-9325-44f760c72e36

**Comment by kahunmedicaltal** [comment]
fixed.
