### ISSUE TITLE
Easier navigation within rules view

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#57]
Could we add a sub-menu on the left panel under RULES?
with the subgroups of rules: EPIDEMIOLOGY, RISK FACTORS, SIGNS, SYMPTOMS, LABS, etc.

With detailed features finding where to click the "add a new rule" is highly time-consuming.

**Comment by kahunmedicaltal** [comment]
@MichalKahun @alex8080 
How about adding a "collapse all / expand all" options in the rule page (+ making sure the headers of the category take less space). This will enable to quickly find the right category and click the new rule button.

**Comment by MichalKahun** [comment]
yes please :))

**Comment by MichalKahun** [comment]
@alex8080 
On the same subject, rules that set a probability for a subset of populations (periods of life, geographic location, ethnic group, etc) take too much space on the screen. Is it possible to display only the values that were filled in the matrix?
Example: 
![image](https://user-images.githubusercontent.com/42371975/50639685-01586b80-0f6b-11e9-96bd-a20025c5fab3.png)

**Comment by kahunmedicaltal** [comment]
Yes. Would be great if you could take case of this as well

**Comment by alex8080** [comment]
Hi @MichalKahun, what is the disorder you are listing? I am trying to find some disorder with such a long rule to test the change.

**Comment by MichalKahun** [comment]
@alex8080 
http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/feature/FE.a9307c50-1aab-48ab-89de-b6070a2538d3

**Comment by alex8080** [comment]
@kahunmedicaltal  I've played yesterday with the "sticky-top" option. On the master branch it does not work for some reason when applied on the rules page. It looks like there is something wrong with the CSS. But it does work on the branch where I re-implemented side navigation menu. If you do not like the new menu, please let me know and I will dig into the reasons "sticky-top" does not work on the main branch.

**Comment by kahunmedicaltal** [comment]
@alex8080 the new side bar looks great. Please go ahead and implement the "sticky-top"

**Comment by MichalKahun** [comment]
the fixed list at the top is great. thank you. 

Can you please move the hyperlink "edit" from the right of the feature name back down a row? 
We use the 'double click' on the feature name numerous times in order to select the feature name, copy, and paste it in another program that we use to search for code (snomed codes).
Now if you double click on the feature name the "edit" hyperlink is also selected. 

Thanks.
