### ISSUE TITLE
deletion of inherited rule

### ISSUE THREAD

**Issue by kahunmedicaltal** [kahunmedical/kne#6]
after setting a disease as CHILD of another disease.
Deleted rule within child.
and the rule was deleted from PARENT
this might be related to the previous bug that does not set the 'is a' relation as we expect.
![44836478-bbe40480-ac3f-11e8-89dd-392cebd7e5f2](https://user-images.githubusercontent.com/42319641/45928924-96eb6480-bf53-11e8-8ce3-fc27eee4621d.png)

**Comment by kahunmedical** [comment]
can we have an option to "un-inherit" a specific rule?
"copy to child" option. this will create a new rule for the child and user will be able to edit the rule, change the probability or removed to rule.
