### ISSUE TITLE
MODERATE: same change appears multiple times

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#63]
This keeps occurring that the same change (always a change that is adding a new feature) appears numerous times. 
example, the change, and a few previous changes are the same: http://kahuneditor.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/commits/commit/CH.9efdbcab-4137-4366-8fff-8b82ac5e9b58

**Comment by kahunmedicaltal** [comment]
someone is clicking submit multiple times. we probably need to enhance the UI (and disable the submit button after the 1st click)
