### ISSUE TITLE
Moderate: onApprove or onReject > move to next change in moderate list

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#66]
a small improvement in the life of a moderator :)
Before I get wrist arthritis from too many mouse clicks :)

**Comment by MichalKahun** [comment]
Any chance this request can get a higher priority? 

When clicking Accept or reject, move to the next change in the moderation list, rather than to the main moderation list view. 

Thanks

**Comment by alex8080** [comment]
@MichalKahun I've submitted the change on January 14th and it was merged on January 23rd. @kahunmedicaltal is it possible that the new code was not released to production?

**Comment by kahunmedicaltal** [comment]
Just deployed new ver to production. Sorry for the delay

**Comment by MichalKahun** [comment]
@alex8080 @kahunmedicaltal 
Thanks. I think there is a bug in the fix. OnApprove does approve the change, but the viewed page is not changed to view the next change in the list. (nothing changes in the screen onApprove)
Am i missing something?

**Comment by alex8080** [comment]
@MichalKahun there is one bad assumption I've made which might be the reason. I assumed that you will approve commits from the oldest to the newest. Now that I think about it I should just roll back to the oldest commit when there are no newer "unapproved" commits. 
Could you check if there are any errors logged to the browser console when you approve a commit, please (because as always "it works on my machine" 😄)?

**Comment by MichalKahun** [comment]
@alex8080 i think your assumption is correct. i go through the commits from oldest to newest. 
This is the error i get when i click on approve (on the 5th commit in the list, as the first 4 commits are errored, cannot be opened)
![image](https://user-images.githubusercontent.com/42371975/52140455-8a8ebb00-265b-11e9-8a47-ac82915f9f52.png)

**Comment by MichalKahun** [comment]
@alex8080 ok, thanks. In that case, we need to force approve the 4 'stuck' commits in the list and the rest should be working as expected.
Thanks, i'll update you once the list is fixed and i see that the change is working fine.
