### ISSUE TITLE
RULES VIEW: in distribution rules, change Overall = 0%

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#72]
@josephmermel 

Either hide Overall = 0%
Or change to overall= 100%

![image](https://user-images.githubusercontent.com/42371975/52551666-2a7bdf80-2de6-11e9-9cbf-9fe527e68bfe.png)

**Comment by josephmermel** [comment]
this was a bug in the editor, so rules already created with this bug have to be manually fixed. But new distribution rules should work correctly
