### ISSUE TITLE
NEW RULE: onUpdate, onDelete > goto RULES VIEW page

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#73]
@josephmermel 

should work the same as onCreate

**Comment by MichalKahun** [comment]
@josephmermel 
HIGH PRIORITY .. disrupts workflow.

**Comment by kahunmedicaltal** [comment]
@alex8080 - it would be great if you can take a look. once you edit a rule and click **update**, **delete** or **create**, upon success you should (1) go back to the original rule**SSS** page (2) see a toast indicating the success.

tnx

tal

**Comment by alex8080** [comment]
Hi @MichalKahun, 

Just want to make sure that I correctly understand your request here. Once a user updates a rule and clicks "update", or deletes a rule do you expect browser to go to the feature (Rules) page? 
The user can navigate to edit a rule through the Moderate page, should we navigate back to the Moderate page in this case or stay on the Rule page?

**Comment by MichalKahun** [comment]
@alex8080 

Hi, 
Yes you are correct. After user clicks Update or delete, if the action was succesful the page should be redirected to the last Feature rules page visited, or to be more precise, the feature page from which the rule was reached from.
Regarding moderation, the rule edit page is reached from the commit page. 
In this case, the redirection should be back to the commit view of the updated/deleted rule. (The one the user came from).
