### ISSUE TITLE
Old EXPOSURE rules are showing up in EPIDEMIOLOGY and ETIOLOGY

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#80]
Example: these should be in EPIDEMIOLOGY only
http://kahuneditor-dev.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/feature/FE.c74353c8-9c1b-47fb-9bb8-3f5230dd9e68

**Comment by josephmermel** [comment]
This can only happen because they are being migrated with TARGET_CAUSES_SOURCE - I don't know enough to say whether that is a good or bad thing? @kahunmedicaltal ?
