### ISSUE TITLE
Cannot delete a relation. 

### ISSUE THREAD

**Issue by MichalKahun** [kahunmedical/kne#81]
Example: cannot delete this relation
http://kahuneditor-dev.s3-website-us-east-1.amazonaws.com/index.html#/w-kahun/relationEdit/RE.9deff985-0d17-41ba-8b66-3ebd47e2183f

**Comment by josephmermel** [comment]
I improved the error msg handling - so now you should be able to see why you cant delete that relation

**Comment by kahunmedicaltal** [comment]
Problem was that the relation had features using it. Once the relation is removed from the feature it can be deleted. Error message should indicate this correctly now
